--// Luau Playground theme / https://play.luau.org/
local color = Color3.fromHex

return table.freeze({
	Background = color("#121215"),
	Text = color("#E1E4E8"),
	Comments = color("#6B737C"),
	Keywords = color("#66A3FF"),
	Functions = color("#FF8FBB"),
	Strings = color("#8DE6A4"),
	NumbersAndBools = color("#BCAAFE"),
	OperatorsAndBrackets = color("#E1E4E8"),
	Selection = color("#2C313A"),
	CurrentLine = color("#1A1A1E"),
	DiagnosticsError = color("#F14C4C"),
	DiagnosticsWarning = color("#CCA700"),
	ScrollbarHandle = color("#414141")
})
